### ISSUE TITLE
No documentation on how to create messages

### ISSUE THREAD

**Issue by devops-ng** [NeilMadden/apisecurityinaction#5]
I believe there's not a single example on how to create a message on chapter 3 (or the whole book). Do you mind you mind to provide one?

**Comment by NeilMadden** [comment]
Good catch. I’ll add some more examples of how to use the API to chapter 2. (There used to be more detailed descriptions of the whole API but it was dropped for space reasons). 

To create a message after you’ve created a space, send a POST request to /spaces/1/messages/ with a JSON body like the following:
```json
{"author": "demo", "message": "Hello, World!”}
```

**Comment by NeilMadden** [comment]
Descriptions on how to use the API have now been added to chapter 2 along with a link to a Postman collection describing the API with requests for every chapter. These changes are in the final copy going into production, not yet in the MEAP.
